#!/usr/bin/env python3
"""Build the "What's New in the Journals" partials from Crossref.

Run from the project root (gm-landing):

    python3 _scripts/fetch-journals.py

Writes two Quarto partials, both included by notes/journals.qmd and the first
also by notes/index.qmd:

    notes/_journals-ticker.qmd   the three-at-a-time vertical ticker
    notes/_journals-list.qmd     the full list, grouped by month

Why Crossref and not the publishers' own RSS: Cambridge Core's feeds
(www.cambridge.org/core/rss/product/id/...) sit behind Cloudflare and answer
403 to anything that is not a browser, CI runners very much included. Crossref
is open, has no rate gate worth worrying about, and covers OUP as well, so one
source serves all four journals. See DECISIONS.md.

Standard library only, deliberately: renv.lock for this site pins nothing but
renv itself and no R runs at render time. Keep it that way.

On any failure this exits non-zero WITHOUT touching the partials, so the copies
committed to the repo are what gets rendered. The workflow step is
continue-on-error for exactly that reason.
"""

import datetime
import html
import json
import ssl
import sys
import urllib.error
import urllib.request

# Add a journal by adding a line. The ISSN is the electronic one; Crossref
# accepts either, and resolves both to the same journal record. The third
# field is what the publisher calls an article that is online but not yet in
# an issue -- Cambridge says FirstView, OUP says Advance Access.
JOURNALS = [
    ("1476-4989", "Political Analysis", "FirstView"),
    ("2052-2649", "Journal of Experimental Political Science", "FirstView"),
    ("1537-5331", "Public Opinion Quarterly", "Advance Access"),
    ("2049-8489", "Political Science Research and Methods", "FirstView"),
]

# How far back to look, and how many articles to keep. The four journals
# together publish roughly eighteen articles a month, so 120 days is a
# comfortable margin over the monthly refresh even if a scheduled run is
# skipped -- GitHub suspends cron after 60 days of no commits.
WINDOW_DAYS = 120
MAX_ITEMS = 40

# Crossref's "polite pool" -- identifying the caller gets more predictable
# service than the anonymous pool.
USER_AGENT = (
    "govtmethods-site/1.0 (https://govtmethods.github.io; "
    "mailto:parushya@gmail.com)"
)

API = "https://api.crossref.org/journals/{issn}/works"
SELECT = "DOI,title,author,volume,issue,page,published"

CONTEXT = None

MONTHS = ["January", "February", "March", "April", "May", "June", "July",
          "August", "September", "October", "November", "December"]

GENERATED_NOTE = (
    "<!-- Generated by _scripts/fetch-journals.py. Do not edit by hand; "
    "CI regenerates it on every build. -->"
)


def ssl_context():
    """Default verification, with certifi if the interpreter has no roots.

    The python.org macOS builds ship without a certificate store until you run
    Install Certificates.command, and an editor should not have to debug that.
    /usr/bin/python3 and the CI runner both verify out of the box.
    """
    context = ssl.create_default_context()
    try:
        context.load_default_certs()
        if not context.get_ca_certs():
            raise ssl.SSLError("no default CA certificates")
    except ssl.SSLError:
        try:
            import certifi
            context = ssl.create_default_context(cafile=certifi.where())
        except ImportError:
            sys.stderr.write(
                "fetch-journals: this Python has no CA certificates. Use "
                "/usr/bin/python3, or run Install Certificates.command.\n")
    return context


def fetch(issn, journal, early, cutoff):
    url = (
        API.format(issn=issn)
        + "?filter=type:journal-article,from-pub-date:" + cutoff
        + "&sort=published&order=desc&rows=50&select=" + SELECT
    )
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=45, context=CONTEXT) as resp:
        payload = json.load(resp)
    return [(journal, early, item) for item in payload["message"]["items"]]


def date_parts(item):
    """(y, m, d) of publication, padded -- Crossref may give only a year."""
    parts = (item.get("published") or {}).get("date-parts") or [[]]
    parts = list(parts[0]) if parts and parts[0] else []
    while len(parts) < 3:
        parts.append(1)
    return tuple(parts[:3])


def authors(item):
    names = []
    for person in item.get("author") or []:
        name = " ".join(
            bit for bit in (person.get("given"), person.get("family")) if bit
        ).strip()
        if not name:
            name = person.get("name") or ""
        if name:
            names.append(name)
    if not names:
        return ""
    if len(names) > 3:
        return ", ".join(names[:3]) + ", et al."
    return ", ".join(names)


def where(item, early):
    """Issue label, or the publisher's name for "not yet in an issue"."""
    volume, issue = item.get("volume"), item.get("issue")
    if volume and issue:
        return "{}({})".format(volume, issue)
    if volume:
        return "Volume {}".format(volume)
    return early


def row(entry):
    journal, early, item = entry
    year, month, day = date_parts(item)
    title = (item.get("title") or ["Untitled"])[0]
    return {
        "sort": (year, month, day),
        "date": "{} {} {}".format(day, MONTHS[month - 1][:3], year),
        "month": "{} {}".format(MONTHS[month - 1], year),
        "url": "https://doi.org/" + item["DOI"],
        "journal": journal,
        "where": where(item, early),
        "title": title,
        "authors": authors(item),
    }


def anchor(r, extra_class=""):
    cls = ("gm-tick " + extra_class).strip()
    return (
        '<a class="{cls}" href="{url}">'
        '<span class="gm-tick-meta">'
        '<span class="gm-tick-date">{date}</span>'
        '<span class="gm-tick-src">{journal} &middot; {where}</span>'
        "</span>"
        '<span class="gm-tick-title">{title}</span>'
        '<span class="gm-tick-authors">{authors}</span>'
        "</a>"
    ).format(
        cls=cls,
        url=html.escape(r["url"], quote=True),
        date=html.escape(r["date"]),
        journal=html.escape(r["journal"]),
        where=html.escape(r["where"]),
        title=html.escape(r["title"]),
        authors=html.escape(r["authors"]),
    )


def ticker_partial(rows, stamp):
    """The journals card: three articles visible, the rest behind them.

    The rotation itself is _includes/gm-ticker.html, shared with the entry
    cards on the same page -- this only marks the card up and declares how
    many rows it shows. The rows are plain anchors in document order, so with
    JavaScript off, or motion reduced, the card is a static list of the three
    newest.
    """
    body = "\n".join("        " + anchor(r) for r in rows)
    return """{note}

```{{=html}}
<div class="gm-card gm-card--wide" data-gm-ticker data-rows="3">
  <span class="gm-card-head">New in the journals</span>
  <div class="gm-ticker" aria-label="Newest journal articles">
    <div class="gm-ticker-track">
{body}
    </div>
  </div>
  <span class="gm-card-foot">Updated {stamp} &middot; source: Crossref &middot; <a href="journals.html">see all new papers &rarr;</a></span>
</div>
```
""".format(note=GENERATED_NOTE, body=body, stamp=stamp)


def list_partial(rows):
    out = [GENERATED_NOTE, "", "```{=html}", '<div class="gm-ticklist">']
    current = None
    for r in rows:
        if r["month"] != current:
            current = r["month"]
            out.append('  <h3 class="gm-tick-month">{}</h3>'.format(
                html.escape(current)))
        out.append("  " + anchor(r, "gm-tick--listed"))
    out += ["</div>", "```", ""]
    return "\n".join(out)


def main():
    global CONTEXT
    CONTEXT = ssl_context()

    today = datetime.date.today()
    cutoff = (today - datetime.timedelta(days=WINDOW_DAYS)).isoformat()

    entries = []
    for issn, journal, early in JOURNALS:
        try:
            entries += fetch(issn, journal, early, cutoff)
        except (urllib.error.URLError, OSError, ValueError, KeyError) as err:
            sys.stderr.write(
                "fetch-journals: {} ({}) failed: {}\n".format(journal, issn, err))
            return 1

    if not entries:
        sys.stderr.write("fetch-journals: no articles returned; keeping the "
                         "committed partials\n")
        return 1

    seen, rows = set(), []
    for entry in entries:
        doi = entry[-1].get("DOI")
        if not doi or doi in seen:
            continue
        seen.add(doi)
        rows.append(row(entry))

    rows.sort(key=lambda r: r["sort"], reverse=True)
    rows = rows[:MAX_ITEMS]

    stamp = "{} {} {}".format(today.day, MONTHS[today.month - 1], today.year)

    with open("notes/_journals-ticker.qmd", "w", encoding="utf-8") as fh:
        fh.write(ticker_partial(rows, stamp))
    with open("notes/_journals-list.qmd", "w", encoding="utf-8") as fh:
        fh.write(list_partial(rows))

    sys.stderr.write("fetch-journals: wrote {} articles from {} journals\n".format(
        len(rows), len(JOURNALS)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
